### ISSUE TITLE
switching the modes in HM-10 modules

### ISSUE THREAD

**Issue by vprithiviraj** [suryasundarraj/hm-10-firmware#1]
How do i switch the mode of module? that is when any data acquisition is over, how should i go for sleep mode. the one way is send AT+SLEEP but if i'm doing that it will transmit the command to the paired module. I'm not able to get out from that issue. can just help me out in that?

**Comment by suryasundarraj** [comment]
Hello @vprithiviraj,  To provide any AT Commands first disconnect from the existing connection and get into Sleep Mode orelse Provide the Voltage to the module from any of the digital Pin and make the Pin Low to turn off the module when it is not required.
